# structurelint configuration
# Comprehensive setup with best practices for pytest-deep-analysis
# Documentation: https://github.com/structurelint/structurelint
#
# Enabled Phases:
# - Phase 0: Filesystem structure validation
# - Phase 1: Architectural layer enforcement
# - Phase 2: Dead code detection
# - Phase 3: Test validation
# - Phase 4: File content templates
# - Phase 8: GitHub workflow enforcement
# - Bonus: Linter configuration enforcement

root: true

exclude:
  - testdata/**
  - .git/**
  - __pycache__/**
  - .pytest_cache/**
  - venv/**
  - .venv/**
  - "*.egg-info/**"
  - build/**
  - dist/**
  - .mypy_cache/**
  - .ruff_cache/**
  - .tox/**
  - htmlcov/**
  - .coverage
  - coverage.xml
  - .structurelint.yml

rules:
  # ==========================================================================
  # Phase 0: Basic Filesystem Structure
  # ==========================================================================

  # Limit directory depth to prevent over-nesting
  max-depth:
    max: 5
    exemptions:
      - ".git/**"
      - "**/__pycache__/**"

  # Keep directories focused - max 30 files per directory
  max-files-in-dir:
    max: 30
    exemptions:
      - "tests/test_harness"  # Test files can have more
      - ".git/**"

  # Limit subdirectories for better organization
  max-subdirs:
    max: 15
    exemptions:
      - ".git/**"

  # Enforce consistent naming conventions
  naming-convention:
    style: "snake_case"
    apply-to:
      - "**/*.py"
    exemptions:
      - "**/__pycache__/**"
      - ".git/**"
      - "README.md"
      - "LICENSE"
      - "CONTRIBUTING.md"
      - "CHANGELOG.md"

  # Ensure critical documentation exists (root level only)
  # Note: file-existence checks all directories - use exemptions
  file-existence:
    "README.md":
      rule: "exists:1"
      exemptions:
        - "pytest_deep_analysis/**"
        - "tests/**"
        - "**/__pycache__/**"
        - "*.egg-info/**"
    "LICENSE":
      rule: "exists:1"
      exemptions:
        - "pytest_deep_analysis/**"
        - "tests/**"
        - "**/__pycache__/**"
        - "*.egg-info/**"
    "pyproject.toml":
      rule: "exists:1"
      exemptions:
        - "pytest_deep_analysis/**"
        - "tests/**"
        - "**/__pycache__/**"
        - "*.egg-info/**"
    ".gitignore":
      rule: "exists:1"
      exemptions:
        - "pytest_deep_analysis/**"
        - "tests/**"
        - "**/__pycache__/**"
        - "*.egg-info/**"

  # Disallow problematic file patterns
  disallowed-patterns:
    - "*.tmp"
    - "*.bak"
    - ".DS_Store"
    - "*.swp"
    - "*.swo"
    - "*~"
    - "Thumbs.db"
    - "*.pyc"
    - "*.pyo"
    - "*.orig"
    - "*.rej"
    - ".idea"
    - ".vscode"  # Encourage using .vscode/ in .gitignore instead

  # Regex pattern enforcement - disallow common anti-patterns
  regex-disallow:
    patterns:
      # Disallow TODO without tracking issue
      - pattern: "# TODO(?!.*#\\d+)"
        message: "TODOs must reference an issue number (e.g., # TODO #123)"
        exemptions:
          - "tests/**"

      # Disallow print() statements in production code
      - pattern: "\\bprint\\("
        message: "Use logging instead of print() statements"
        exemptions:
          - "tests/**"
          - "scripts/**"
          - "**/__main__.py"

      # Disallow hardcoded secrets patterns
      - pattern: "(password|secret|key)\\s*=\\s*['\"][^'\"]{8,}"
        message: "Potential hardcoded secret detected - use environment variables"
        exemptions:
          - "tests/**"
          - "**/conftest.py"

  # ==========================================================================
  # Phase 3: Test Validation
  # ==========================================================================

  # Test adjacency for Python with integration test pattern
  test-adjacency:
    pattern: "separate"
    test-dir: "tests"
    file-patterns:
      - "**/*.py"
    exemptions:
      # Package/module structure files
      - "**/__init__.py"
      - "**/conftest.py"
      - "setup.py"

      # Plugin entry points (tested via integration tests)
      - "pytest_deep_analysis/__init__.py"
      - "pytest_deep_analysis/runtime/__init__.py"

      # Message definitions (no logic to test)
      - "pytest_deep_analysis/messages.py"

      # Main implementation files are tested via integration tests in test_harness
      # This is a valid pattern for linters/checkers
      - "pytest_deep_analysis/checkers.py"
      - "pytest_deep_analysis/config.py"
      - "pytest_deep_analysis/utils.py"

      # Runtime components tested via integration
      - "pytest_deep_analysis/runtime/*.py"

  # Test location validation
  test-location:
    integration-test-dir: "tests"
    allow-adjacent: false
    exemptions:
      - "testdata/**"
      - "examples/**"

  # ==========================================================================
  # Phase 1: Architectural Layers (Python Linter)
  # ==========================================================================

  layers:
    # Public API layer
    - name: "api"
      paths:
        - "pytest_deep_analysis/__init__.py"
      can-import:
        - "checkers"
        - "config"
      description: "Public plugin API"

    # Core linting logic
    - name: "checkers"
      paths:
        - "pytest_deep_analysis/checkers.py"
      can-import:
        - "messages"
        - "utils"
        - "config"
      cannot-import:
        - "runtime"  # Static analysis shouldn't depend on runtime
      description: "Core static analysis checker"

    # Utility layer
    - name: "utils"
      paths:
        - "pytest_deep_analysis/utils.py"
      can-import: []  # Pure utilities, no internal deps
      description: "AST/astroid utilities"

    # Configuration layer
    - name: "config"
      paths:
        - "pytest_deep_analysis/config.py"
      can-import: []  # Config is independent
      description: "Configuration management"

    # Message definitions
    - name: "messages"
      paths:
        - "pytest_deep_analysis/messages.py"
      can-import: []  # Pure data, no deps
      description: "Linter message definitions"

    # Runtime validation (separate from static analysis)
    - name: "runtime"
      paths:
        - "pytest_deep_analysis/runtime/*.py"
      can-import:
        - "config"
      cannot-import:
        - "checkers"  # Runtime shouldn't depend on static checker
      description: "Pytest runtime plugin for semantic validation"

  # ==========================================================================
  # Phase 2: Dead Code Detection
  # ==========================================================================

  entrypoints:
    # Plugin entry points
    - "pytest_deep_analysis/__init__.py"
    - "pytest_deep_analysis/runtime/__init__.py"

    # Setup entry points
    - "setup.py"

    # Test entry points
    - "tests/**/test_*.py"
    - "tests/**/*_test.py"
    - "tests/**/conftest.py"

  # Detect orphaned files (files never imported by other files)
  # Note: Disabled for Python projects as plugin entry points and pytest test
  # discovery don't use explicit imports
  disallow-orphaned-files: false

  # Detect unused exports (symbols exported but never imported)
  # Note: Disabled for Python projects as plugin entry points and pytest test
  # classes are discovered rather than imported
  disallow-unused-exports: false

  # ==========================================================================
  # Code Quality: Cognitive Complexity
  # ==========================================================================

  # TODO: Reduce complexity in checker.py enhancement functions
  # Current max set to 50 to allow for complex AST analysis patterns
  # Most functions should target 25 or lower
  max-cognitive-complexity:
    max: 50  # Allows for complex AST analysis in checkers.py
    exemptions:
      - "tests/**"
      - "**/__init__.py"

  # ==========================================================================
  # Code Quality: Halstead Effort (maintainability metric)
  # ==========================================================================

  max-halstead-effort:
    max: 50000  # Functions exceeding this are hard to maintain
    exemptions:
      - "tests/**"
      - "**/__init__.py"

# ==========================================================================
# GitHub Workflow Enforcement (Phase 8)
# ==========================================================================

github-workflows:
  # Require test execution workflow
  require-tests: true

  # Require code quality workflow (linting, formatting, static analysis)
  require-quality: true

  # Require security scanning workflow
  require-security: false  # Optional - enable for production projects

  # Require specific jobs in workflows
  required-jobs:
    - name: "test"
      description: "Must run tests"
    - name: "lint"
      description: "Must run linter"

  # Require specific workflow triggers
  required-triggers:
    - "pull_request"
    - "push"

  # Security scanning requirements (optional)
  security-scanning:
    require-codeql: false
    require-dependency-review: false
    require-secret-scanning: false

# ==========================================================================
# Linter Configuration Enforcement
# ==========================================================================

linter-config:
  # Require Python linter configuration
  # Checks for: pyproject.toml, .flake8, .pylintrc, mypy.ini, ruff.toml
  # OR GitHub workflow running: mypy, black, ruff, pylint, flake8
  require-python: true

# ==========================================================================
# File Content Templates (Phase 4)
# ==========================================================================

file-templates:
  "README.md":
    required-sections:
      - "Installation"
      - "Usage"
      - "Examples"
      - "Configuration"
    description: "Main project documentation must be comprehensive"

  "CONTRIBUTING.md":
    required-sections:
      - "Development"
      - "Testing"
      - "Code Style"
    description: "Contributor guide must cover key workflows"

  "pyproject.toml":
    required-sections:
      - "[build-system]"
      - "[project]"
    description: "Modern Python packaging format"

  ".github/workflows/*.yml":
    forbidden-patterns:
      - "uses: .*@master"  # Require pinned versions
    allowed-patterns:
      - "uses: actions/"  # Official actions
    description: "Workflows must use pinned action versions"

# ==========================================================================
# Overrides for Specific File Patterns
# ==========================================================================

overrides:
  # Test files can be more flexible
  - files:
      - "tests/**"
      - "**/*_test.py"
      - "**/test_*.py"
    rules:
      # Tests don't need __init__.py
      file-existence: 0
      # Tests can have slightly deeper nesting
      max-depth: { max: 6 }
      # Allow more files in test directories
      max-files-in-dir: { max: 40 }
      # Disable dead code detection for tests
      disallow-orphaned-files: false
      disallow-unused-exports: false
      # Allow print statements in tests
      regex-disallow: 0
      # Tests can have higher complexity
      max-cognitive-complexity: { max: 100 }

  # Scripts and tools can have different rules
  - files:
      - "scripts/**"
      - "tools/**"
    rules:
      file-existence: 0
      naming-convention: 0
      test-adjacency: 0
      disallow-orphaned-files: false
      max-cognitive-complexity: { max: 50 }

  # Runtime plugin can have separate architectural rules
  - files:
      - "pytest_deep_analysis/runtime/**"
    rules:
      max-depth: { max: 4 }

  # Allow higher complexity for main checker file (AST analysis)
  - files:
      - "pytest_deep_analysis/checkers.py"
    rules:
      max-cognitive-complexity: { max: 50 }
      max-halstead-effort: { max: 100000 }

  # Configuration files don't need tests
  - files:
      - "**/config.py"
      - "**/settings.py"
      - "**/__init__.py"
      - "**/conftest.py"
    rules:
      test-adjacency: 0
